server:
  port: 8080

spring:
  application:
    name: api-gateway

  cloud:
    gateway:
      routes:
        - id: auth-service
          uri: http://${AUTH_SERVICE_HOST:auth-service}:8081
          predicates:
            - Path=/api/auth/**

        - id: course-service
          uri: http://${COURSE_SERVICE_HOST:course-service}:8082
          predicates:
            - Path=/api/courses/**, /api/lessons/**, /api/categories/**

        - id: enrollment-service
          uri: http://${ENROLLMENT_SERVICE_HOST:enrollment-service}:8083
          predicates:
            - Path=/api/enrollments/**

        - id: course-uploads
          uri: http://${COURSE_SERVICE_HOST:course-service}:8082
          predicates:
            - Path=/uploads/**

jwt:
  secret: ${JWT_SECRET:mi-clave-secreta-para-desarrollo-local-minimo-32-chars}