server:
  port: 8080

spring:
  application:
    name: api-gateway

  cloud:
    gateway:
      httpclient:
        connect-timeout: 120000
        response-timeout: 120s
        follow-redirects: true
        ssl:
          use-insecure-trust-manager: true
      globalcors:
        add-to-simple-url-handler-mapping: true
        cors-configurations:
          '[/**]':
            allowed-origin-patterns:
              - "https://microservices-project-edu-track.vercel.app"
              - "https://*.vercel.app"
              - "https://*.onrender.com"
              - "http://localhost:3000"
              - "http://localhost:5173"
            allowed-methods: "*"
            allowed-headers: "*"
            allow-credentials: true
      routes:
        - id: auth-service
          uri: ${AUTH_SERVICE_URL:http://auth-service:8081}
          predicates:
            - Path=/api/auth/**

        - id: course-service
          uri: ${COURSE_SERVICE_URL:http://course-service:8082}
          predicates:
            - Path=/api/courses/**, /api/lessons/**, /api/categories/**

        - id: enrollment-service
          uri: ${ENROLLMENT_SERVICE_URL:http://enrollment-service:8083}
          predicates:
            - Path=/api/enrollments/**

        - id: course-uploads
          uri: ${COURSE_SERVICE_URL:http://course-service:8082}
          predicates:
            - Path=/uploads/**

jwt:
  secret: ${JWT_SECRET:mi-clave-secreta-para-desarrollo-local-minimo-32-chars}